########################################################################################################################
#
#  Copyright (C) 2010-2013 by the Stratosphere project (http://stratosphere.eu)
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
#  the License. You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
#  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
#  specific language governing permissions and limitations under the License.
#
########################################################################################################################

# s3 deployment based on http://about.travis-ci.org/blog/2012-12-18-travis-artifacts/

language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
env:
    global: 
        # username and password for sonatype (maven delpoy)
        - secure: "QoLd3npmApUw20q+KTt+6Il07bn/edl5pP3jmEqR+rXQXVA2kogjkZerZ5QdM2iQJha7D1M2Y4BTcsJ2Ty7biTxUZkDl+RXz6kpeHPX2alax/KO7mqrJuEfuPAQvaIdHNmKEmdiU/fLMn2q2HllE5MP7FzUNKD5YJIzh1IekPA8="
        - secure: "WzMGwNwWwWw62kwvknMGS4W1zy3oRVihitCjjd5wqk/4JMTeWr+oAMv0GfA8GbOuOcYwA7JNxGXQlBMtn45+/PMLJgnsLxYUbqCD2ybwMBLlnembGYoRPABp5zkuzRmU3G2cbMdu/7VwvlTffEPPG/jqAFLKxmvG0oIOtPtk3lg="
        # New s3 deployment
        - ARTIFACTS_S3_BUCKET="stratosphere-bin"
        - secure: "An/pEveBDMBl6FcZimTfZBAvevAVgkwS2tSAzFblJzp5aofghPORIXiqW/2Dy4ksFkGDK2Yb6QaGXbqC3mbWcPQh7YYeiPbvRipDXe4D+emgoUAiuuxCGvqtgzKxb0VeBeCqrMuNOoO4yLeCXgNZBuZ3B8LjQQCpAyyCWW1f/yo="
        - secure: "fT1qY3/JbDCL+o+XXkU92fuMrZehkLntu8DRNyCeq1eB9SOH/QA7+3S6S2kZZ++aWaTxXKy65V9rO9DWra+KMgeDDkM+ykoSq4CeTjZso5ZXf0GDa2RcnZ5d5BN8UVV/2iyp79ZrQPy7Yer9MrGhrjC5Mo5cFbxoNbn5UV7Y9Uc="
    matrix:
        - PROFILE=
        - PROFILE="-Dhadoop.profile=2"

before_script:
   - "gem install --version 0.8.9 faraday"
   - "gem install travis-artifacts & "


install: true

script: "mvn -B $PROFILE clean verify"

# deploy if the first job is successful; should be replaced by an after_all_success if travis finally supports it
after_success: 
- "./tools/deploy_to_maven.sh"
